version: "3.9"

services:
  php:
    build:
        context: .
        dockerfile: dockerfile
    ports:
      - 3010:80
    volumes:
      - ./html:/var/www/web/
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - sqlData:/var/lib/mysql
    ports:
      - 3020:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 3030:8080


volumes:
    sqlData: